import type { AiNativeEngineeringContent } from './content-types.ts'

export const aiNativeEngineeringContent = {
  meta: {
    classification: 'reconstructed-public-example',
    disclosure: '실제 업무 데이터와 식별정보 없이 개발 판단 구조만 재구성했습니다.',
    boundary: {
      dataOrigin: 'independently-authored-synthetic',
      privateSourceRuntimeDependency: false,
      containsRealIdentifiers: false,
      oneToOneInternalMapping: false,
    },
  },
  hero: {
    eyebrow: 'HOW I BUILD / 02',
    titleLines: ['AI-NATIVE', 'ENGINEERING'],
    thesis: 'AI를 많이 쓰는 것보다, AI가 안정적으로 일할 환경을 먼저 설계했다.',
    summary:
      '저장소의 읽기 순서와 제약을 문서로 고정하고, 코드 수준 맥락과 격리된 실행 환경을 연결한다. 결과는 코드·데이터·테스트로 반박한 뒤에만 기준 맥락으로 돌아간다.',
    manifest: {
      eyebrow: 'BEFORE THE FIRST PROMPT',
      title: 'CONTEXT MANIFEST',
      items: [
        {
          index: '01',
          label: 'INSTRUCTIONS',
          title: 'CLAUDE.md / AGENTS.md',
          description: '도구별 진입점과 공통 작업 규칙, 읽기 순서, 권한 경계를 먼저 제공한다.',
          signals: ['READ ORDER', 'CONSTRAINTS', 'VERIFICATION'],
        },
        {
          index: '02',
          label: 'STRUCTURE',
          title: 'CODEMAP',
          description: '파일을 열기 전에 코드의 역할과 영향 경로, 검증 근거를 탐색한다.',
          signals: ['ROLE', 'ENTRYPOINT', 'DEPENDENCY', 'TESTS', 'CONSTRAINTS', 'EVIDENCE'],
        },
        {
          index: '03',
          label: 'EXECUTION',
          title: 'WORKTREE / BASELINE',
          description: '작업 변경과 기존 상태를 분리하고, 환경 차이가 원인에 섞이지 않았는지 비교한다.',
          signals: ['BRANCH', 'DIRTY STATE', 'ENVIRONMENT'],
        },
      ],
      statusLabel: 'READY WHEN',
      status: 'BASELINE · FRESHNESS · SCOPE가 확인됐을 때',
    },
  },
  scene: {
    eyebrow: 'EXECUTION TRACE / ONE BOUNDED CHANGE',
    title: '한 번의 변경이 기준 맥락으로 돌아오기까지.',
    situation:
      '공개용 재구성 장면: 권한 경계 하나가 화면, 정책, 서비스, 저장 계약과 테스트에 이어지는 작업.',
    toolRule:
      '도구가 시작점은 아니다. 읽기 범위, 변경 권한과 검증 대상을 먼저 정한 뒤 작업 성격에 맞춰 Claude Code 또는 Codex를 선택한다. 둘은 같은 맥락 계약 안에서 일한다.',
    stateLegend: [
      { state: 'context', label: 'KNOWN CONTEXT' },
      { state: 'candidate', label: 'AI CANDIDATE' },
      { state: 'evidence', label: 'EVIDENCE' },
      { state: 'decision', label: 'HUMAN-CONFIRMED' },
      { state: 'canonical', label: 'CANONICAL' },
    ],
    steps: [
      {
        id: 'context',
        label: 'CONTEXT',
        summary: '현재 기준부터 읽는다.',
        action: '원격 기준과 작업 상태를 비교하고, 작업 지침이 지정한 순서로 현재 문서와 known issue를 읽는다.',
        proof: '작업 전제, 아직 확인되지 않은 항목과 금지된 변경이 구분된다.',
        exitRule: '기준 branch, 문서 freshness와 작업 제약을 설명할 수 있을 때.',
        codemapUse: 'LOCK의 생성 범위와 freshness를 먼저 확인한다.',
        state: 'context',
      },
      {
        id: 'scope',
        label: 'SCOPE',
        summary: '영향 범위를 좁힌다.',
        action: '요청과 직접 연결된 entrypoint, dependency, constraint와 test를 찾고 작업 밖의 영역을 명시한다.',
        proof: '수정 대상과 함께 건드리면 안 되는 경계가 작은 변경 단위로 남는다.',
        exitRule: '변경 파일보다 먼저 영향 경로와 검증 surface가 정해졌을 때.',
        codemapUse: 'role, entrypoint, dependency, tests, constraints와 evidence를 한 묶음으로 대조한다.',
        state: 'context',
      },
      {
        id: 'isolate',
        label: 'ISOLATE',
        summary: '코드와 환경의 경계를 나눈다.',
        action: 'Orca/ADE의 독립 worktree에서 branch와 변경 상태를 고정하고, 환경 입력은 clean baseline과 따로 비교한다.',
        proof: '변경, 기존 상태와 로컬 환경을 서로 다른 원인 후보로 추적할 수 있다.',
        exitRule: '재현 명령과 비교 기준이 같은 조건으로 준비됐을 때.',
        state: 'candidate',
      },
      {
        id: 'build',
        label: 'BUILD',
        summary: '검증 가능한 후보를 만든다.',
        action: 'AI가 코드와 테스트 후보를 만들되, 요청한 범위 밖의 구조나 운영 상태는 추정하지 않는다.',
        proof: 'diff와 함께 무엇을 가정했고 무엇을 아직 모르는지가 남는다.',
        exitRule: '후보가 독립적으로 검사 가능하고 되돌릴 수 있을 때.',
        state: 'candidate',
      },
      {
        id: 'verify',
        label: 'VERIFY',
        summary: '코드·데이터·테스트로 반박한다.',
        action: '정적 검사와 관련 테스트를 실행하고, 필요한 경우 실제 데이터 계약 또는 clean baseline과 결과를 비교한다.',
        proof: '초기 가설을 지지하거나 반박하는 관찰 결과가 명령과 함께 남는다.',
        exitRule: '성공뿐 아니라 실패 원인과 검증하지 못한 범위까지 설명할 수 있을 때.',
        codemapUse: '처음 식별한 영향 경로에 검증 누락이 없는지 다시 대조한다.',
        state: 'evidence',
      },
      {
        id: 'decision',
        label: 'HUMAN DECISION',
        summary: '채택 여부를 사람이 판단한다.',
        action: '근거를 바탕으로 채택, 수정 또는 보류를 결정한다. 생성됐거나 테스트가 통과했다는 사실만으로 승인하지 않는다.',
        proof: 'AI candidate와 human-confirmed 결과의 경계가 기록된다.',
        exitRule: '결정 주체와 근거, 남은 위험이 함께 확인됐을 때.',
        state: 'decision',
      },
      {
        id: 'canonicalize',
        label: 'CANONICALIZE',
        summary: '확인된 것만 다시 기준으로 남긴다.',
        action: '확정된 변경이 구조나 경계를 바꿨다면 작업 지침, 관련 문서와 코드 수준 맥락을 같은 변경에서 갱신한다.',
        proof: '다음 작업이 새 기준을 다시 찾을 수 있고 stale 여부를 확인할 수 있다.',
        exitRule: '코드, 문서와 freshness contract가 같은 사실을 가리킬 때.',
        codemapUse: 'Codemap을 갱신하고 새 LOCK, scan scope와 fingerprint를 확인한다.',
        state: 'canonical',
      },
    ],
  },
  incident: {
    eyebrow: 'FAILURE RECORD / ENVIRONMENT LEAK',
    title: 'Worktree가 분리돼 있어도, 환경까지 깨끗한 것은 아니었다.',
    summary:
      '격리된 작업에서 테스트가 예상과 다르게 움직였다. 코드 회귀로 단정하지 않고 clean baseline과 같은 검증 명령을 비교해 원인을 다시 나눴다.',
    symptom: '독립 worktree의 테스트 결과가 기존 기준과 다르게 나타남.',
    hypotheses: ['코드 변경의 회귀', 'fixture 또는 dependency 차이', '상속된 .env 입력의 오염'],
    comparison: [
      {
        id: 'working-copy',
        label: 'ISOLATED WORKTREE',
        state: 'UNEXPECTED',
        observation: '변경 branch와 로컬 환경 입력이 함께 있는 상태에서는 이상 동작이 재현됐다.',
      },
      {
        id: 'clean-baseline',
        label: 'CLEAN BASELINE',
        state: 'EXPECTED',
        observation: '깨끗한 기준에서는 같은 검증 명령이 정상 동작했고, 환경 입력 차이가 남았다.',
      },
    ],
    evidence:
      'branch diff만으로는 증상이 설명되지 않았고, 결과 차이는 코드보다 .env 조건을 따라 움직였다.',
    decision: '기능 코드 수정 전에 오염된 환경을 별도 원인으로 분리했다.',
    rule: ['ISOLATE CODE.', 'VERIFY ENVIRONMENT.'],
  },
  artifacts: {
    eyebrow: 'THREE CONTROLS / HUMAN + AI',
    title: '같이 읽되, 서로 다른 책임을 맡는 세 가지 artifact.',
    introduction:
      '문서는 많이 쌓는 대신, 작업을 시작하게 하는 것·영향을 찾게 하는 것·원인을 분리하게 하는 것으로 책임을 나눴다.',
    items: [
      {
        index: 'A1',
        label: 'ENTRY CONTRACT',
        title: 'CLAUDE.md / AGENTS.md',
        question: '어디서부터 읽고, 어떤 권한과 검증 규칙으로 일하는가?',
        responsibility: 'Claude Code 전용 진입점과 공통 AI agent 규칙을 분리하되, 같은 프로젝트 경계로 수렴시킨다.',
        maintenance: '읽기 순서, AI agent 분기, 안전 경계 또는 완료 조건이 바뀔 때 갱신.',
      },
      {
        index: 'A2',
        label: 'STRUCTURAL CONTRACT',
        title: 'CODEMAP / JSON + LOCK',
        question: '무엇이 이 코드를 호출하고, 어디에 영향을 주며, 무엇이 검증하는가?',
        responsibility: '사람과 agent가 같은 코드 문맥을 조회하고, LOCK으로 생성 범위와 freshness를 확인한다.',
        maintenance: 'module boundary, dependency, route, data contract 또는 주요 flow가 바뀔 때 갱신.',
        fields: ['ROLE', 'ENTRYPOINT', 'DEPENDENCY', 'TESTS', 'CONSTRAINTS', 'EVIDENCE'],
        href: '/how/documentation-system/artifacts/codemap',
      },
      {
        index: 'A3',
        label: 'ISOLATION CONTRACT',
        title: 'WORKTREE / CLEAN BASELINE',
        question: '지금 보는 증상은 코드, 데이터, dependency, 환경 중 어디에서 왔는가?',
        responsibility: 'Orca/ADE worktree로 변경을 나누고, clean baseline 비교로 로컬 환경의 영향을 별도 가설로 검증한다.',
        maintenance: '실행 환경, fixture, dependency 또는 검증 명령이 달라질 때 비교 조건을 갱신.',
      },
    ],
  },
  principle: {
    eyebrow: 'BOUNDARY / CURRENT PRACTICE',
    statement: 'AI-ready는 모델 선택이 아니라, 환경의 상태다.',
    explanation:
      '현재 맥락을 찾을 수 있고, 변경이 격리되며, 검증 가능한 출구조건이 있을 때 AI는 반복 가능한 협업자가 된다.',
    maintenanceRule: {
      label: 'CURRENT RULE',
      statement: 'CHANGE → CONTEXT → VERIFY',
      detail: '확인된 구조 변경은 코드와 같은 변경에서 작업 지침과 Codemap에 반영하고, 다음 작업 전에 다시 freshness를 확인한다.',
    },
    boundary: [
      '문서와 Codemap은 방향을 제공하지만 코드·데이터·테스트를 대신하는 proof는 아니다.',
      'AI candidate, 검증 evidence, human-confirmed decision과 canonical context를 서로 다른 상태로 유지한다.',
      '구현과 테스트 통과는 deployment, runtime use 또는 adoption을 의미하지 않는다.',
      '생산성·정확도·시간 단축 효과는 측정하지 않았으므로 주장하지 않는다.',
    ],
    appliedIn: '제품 사례 연결은 공개용 근거와 페이지가 준비된 뒤 엽니다.',
  },
} as const satisfies AiNativeEngineeringContent
