import type { AiNativeEngineeringContent } from './content-types.ts'

export const aiNativeEngineeringContent = {
  meta: {
    classification: 'reconstructed-public-example',
    disclosure: '실제 업무 데이터와 식별정보 없이 개발 판단 구조만 재구성했습니다.',
    boundary: {
      dataOrigin: 'independently-authored-synthetic',
      privateSourceRuntimeDependency: false,
      containsRealIdentifiers: false,
      oneToOneInternalMapping: false,
    },
  },
  hero: {
    eyebrow: 'HOW I BUILD / 02',
    titleLines: ['AI-NATIVE', 'ENGINEERING'],
    thesis: 'AI가 읽을 기준, 바꿀 범위, 검증할 조건을 먼저 정했다.',
    summary:
      '읽기 순서와 작업 제약을 문서에 남기고, 코드의 영향 경로를 확인한다. 작업별로 변경을 분리해 만든 결과는 코드·데이터·테스트로 검증하고, 사람이 채택한 뒤 기준 문서에 반영한다.',
    manifest: {
      eyebrow: '작업을 시작하기 전에',
      title: 'AI가 참고할 작업 기준',
      items: [
        {
          index: '01',
          label: 'INSTRUCTIONS',
          title: 'CLAUDE.md / AGENTS.md',
          description: '도구별 진입점과 공통 작업 규칙, 읽기 순서, 권한 경계를 먼저 제공한다.',
          signals: ['READ ORDER', 'CONSTRAINTS', 'VERIFICATION'],
        },
        {
          index: '02',
          label: 'STRUCTURE',
          title: 'CODEMAP',
          description: '파일을 열기 전에 코드의 역할과 영향 경로, 검증 근거를 탐색한다.',
          signals: ['ROLE', 'ENTRYPOINT', 'DEPENDENCY', 'TESTS', 'CONSTRAINTS', 'EVIDENCE'],
        },
        {
          index: '03',
          label: 'EXECUTION',
          title: 'WORKTREE / BASELINE',
          description: '작업 변경과 기존 상태를 분리하고, 환경 차이가 원인에 섞이지 않았는지 비교한다.',
          signals: ['BRANCH', 'DIRTY STATE', 'ENVIRONMENT'],
        },
      ],
      statusLabel: 'READY WHEN',
      status: '변경 전 기준·문서 최신성·작업 범위가 확인됐을 때',
    },
  },
  scene: {
    eyebrow: 'EXECUTION TRACE / ONE BOUNDED CHANGE',
    title: '한 번의 변경을 검증하고 기준 문서에 반영하기까지.',
    situation:
      '권한 조건 하나를 바꿀 때 화면·정책·서비스·저장 규칙·테스트를 함께 검토하는 공개 재구성 사례.',
    toolRule:
      '읽을 범위, 변경 권한, 검증 대상을 먼저 정하고 작업에 맞춰 Claude Code 또는 Codex를 사용한다. 두 도구에 같은 프로젝트 지침을 적용한다.',
    stateLegend: [
      { state: 'context', label: '작업 기준' },
      { state: 'candidate', label: 'AI가 만든 후보' },
      { state: 'evidence', label: '검증 근거' },
      { state: 'decision', label: '사람이 채택한 변경' },
      { state: 'canonical', label: '기준에 반영됨' },
    ],
    steps: [
      {
        id: 'context',
        label: 'CONTEXT',
        summary: '현재 기준부터 읽는다.',
        action: '원격 기준과 작업 상태를 비교하고, 작업 지침의 순서대로 현재 문서와 알려진 문제를 읽는다.',
        proof: '작업 전제, 아직 확인되지 않은 항목과 금지된 변경이 구분된다.',
        exitRule: '기준 브랜치·문서 최신성·작업 제약을 설명할 수 있을 때.',
        codemapUse: 'LOCK에서 생성 범위와 최신성을 먼저 확인한다.',
        state: 'context',
      },
      {
        id: 'scope',
        label: 'SCOPE',
        summary: '영향 범위를 좁힌다.',
        action: '요청과 연결된 진입점·의존성·제약·테스트를 찾고, 변경하지 않을 영역을 명시한다.',
        proof: '수정 대상과 함께 건드리면 안 되는 경계가 작은 변경 단위로 남는다.',
        exitRule: '영향 경로와 검증할 대상이 정해졌을 때.',
        codemapUse: '코드의 역할·진입점·의존성·테스트·제약·근거를 함께 대조한다.',
        state: 'context',
      },
      {
        id: 'isolate',
        label: 'ISOLATE',
        summary: '코드와 환경의 경계를 나눈다.',
        action: 'Orca/ADE의 독립 worktree에서 브랜치와 변경 상태를 고정한다. 환경 입력은 변경 전 기준과 별도로 비교한다.',
        proof: '변경, 기존 상태와 로컬 환경을 서로 다른 원인 후보로 추적할 수 있다.',
        exitRule: '재현 명령과 비교 기준이 같은 조건으로 준비됐을 때.',
        state: 'candidate',
      },
      {
        id: 'build',
        label: 'BUILD',
        summary: '검증 가능한 후보를 만든다.',
        action: 'AI가 코드와 테스트 후보를 만들되, 요청한 범위 밖의 구조나 운영 상태는 추정하지 않는다.',
        proof: '변경 내용과 함께 가정한 것과 아직 확인하지 못한 것을 남긴다.',
        exitRule: '후보가 독립적으로 검사 가능하고 되돌릴 수 있을 때.',
        state: 'candidate',
      },
      {
        id: 'verify',
        label: 'VERIFY',
        summary: '코드·데이터·테스트로 검증한다.',
        action: '정적 검사와 관련 테스트를 실행하고, 필요하면 실제 데이터 규칙이나 변경 전 기준과 결과를 비교한다.',
        proof: '초기 가설을 지지하거나 반박하는 관찰 결과가 명령과 함께 남는다.',
        exitRule: '성공뿐 아니라 실패 원인과 검증하지 못한 범위까지 설명할 수 있을 때.',
        codemapUse: '처음 식별한 영향 경로에 검증 누락이 없는지 다시 대조한다.',
        state: 'evidence',
      },
      {
        id: 'decision',
        label: 'HUMAN DECISION',
        summary: '채택 여부를 사람이 판단한다.',
        action: '근거를 바탕으로 채택, 수정 또는 보류를 결정한다. 생성됐거나 테스트가 통과했다는 사실만으로 승인하지 않는다.',
        proof: 'AI가 만든 후보 중 무엇을 사람이 채택했는지 기록한다.',
        exitRule: '결정 주체와 근거, 남은 위험이 함께 확인됐을 때.',
        state: 'decision',
      },
      {
        id: 'canonicalize',
        label: 'CANONICALIZE',
        summary: '확인된 것만 다시 기준으로 남긴다.',
        action: '확정된 변경이 구조나 경계를 바꿨다면 작업 지침, 관련 문서와 코드 수준 맥락을 같은 변경에서 갱신한다.',
        proof: '다음 작업에서 새 기준을 찾고, 코드와 문서가 어긋났는지 확인할 수 있다.',
        exitRule: '코드·문서·생성 기준이 같은 변경을 가리킬 때.',
        codemapUse: 'Codemap을 갱신하고 새 LOCK의 스캔 범위와 모듈 지문을 확인한다.',
        state: 'canonical',
      },
    ],
  },
  incident: {
    eyebrow: 'FAILURE RECORD / ENVIRONMENT LEAK',
    title: 'Worktree가 분리돼 있어도, 환경까지 깨끗한 것은 아니었다.',
    summary:
      '격리된 작업에서 테스트가 예상과 다르게 움직였다. 변경 전 기준에서도 같은 검증 명령을 실행해 코드와 환경의 영향을 나눴다.',
    symptom: '독립 worktree의 테스트 결과가 기존 기준과 다르게 나타남.',
    hypotheses: ['코드 변경의 회귀', '테스트 데이터 또는 의존성 차이', '상속된 .env 입력의 오염'],
    comparison: [
      {
        id: 'working-copy',
        label: 'ISOLATED WORKTREE',
        state: 'UNEXPECTED',
        observation: '변경 브랜치와 로컬 환경 입력이 함께 있는 상태에서 이상 동작이 재현됐다.',
      },
      {
        id: 'clean-baseline',
        label: 'CLEAN BASELINE',
        state: 'EXPECTED',
        observation: '깨끗한 기준에서는 같은 검증 명령이 정상 동작했고, 환경 입력 차이가 남았다.',
      },
    ],
    evidence:
      '브랜치의 코드 차이만으로는 증상을 설명할 수 없었다. 결과는 .env 조건에 따라 달라졌다.',
    decision: '기능 코드 수정 전에 오염된 환경을 별도 원인으로 분리했다.',
    rule: ['ISOLATE CODE.', 'VERIFY ENVIRONMENT.'],
  },
  artifacts: {
    eyebrow: 'THREE CONTROLS / HUMAN + AI',
    title: '작업 지침, 코드 지도, 비교 기준의 역할',
    introduction:
      '작업 지침은 읽기 순서와 권한을, Codemap은 영향 경로를, 변경 전 기준은 원인을 비교할 조건을 맡는다.',
    items: [
      {
        index: 'A1',
        label: 'ENTRY CONTRACT',
        title: 'CLAUDE.md / AGENTS.md',
        question: '어디서부터 읽고, 어떤 권한과 검증 규칙으로 일하는가?',
        responsibility: 'Claude Code 전용 진입점과 공통 AI 작업 규칙을 구분하고, 같은 프로젝트 제약을 적용한다.',
        maintenance: '읽기 순서·도구별 작업 규칙·변경 권한·완료 조건이 바뀔 때 갱신.',
      },
      {
        index: 'A2',
        label: 'STRUCTURAL CONTRACT',
        title: 'CODEMAP / JSON + LOCK',
        question: '무엇이 이 코드를 호출하고, 어디에 영향을 주며, 무엇이 검증하는가?',
        responsibility: '사람과 개발 에이전트가 같은 코드 지도를 읽고, LOCK으로 생성 범위와 최신성을 확인한다.',
        maintenance: '모듈 경계·의존성·라우트·데이터 규칙·주요 흐름이 바뀔 때 갱신.',
        fields: ['ROLE', 'ENTRYPOINT', 'DEPENDENCY', 'TESTS', 'CONSTRAINTS', 'EVIDENCE'],
        href: '/how/documentation-system/artifacts/codemap',
      },
      {
        index: 'A3',
        label: 'ISOLATION CONTRACT',
        title: 'WORKTREE / CLEAN BASELINE',
        question: '지금 보는 증상은 코드·데이터·의존성·환경 중 어디에서 왔는가?',
        responsibility: 'Orca/ADE worktree로 변경을 분리하고, 변경 전 기준과 비교해 로컬 환경의 영향을 검증한다.',
        maintenance: '실행 환경·테스트 데이터·의존성·검증 명령이 달라질 때 비교 조건을 갱신.',
      },
    ],
  },
  principle: {
    eyebrow: 'BOUNDARY / CURRENT PRACTICE',
    statement: 'AI-ready는 모델 선택이 아니라, 환경의 상태다.',
    explanation:
      '작업 시작 전에는 기준과 범위를, 반영 전에는 검증 결과와 사람의 결정을 확인한다.',
    maintenanceRule: {
      label: 'CURRENT RULE',
      statement: 'CHANGE → CONTEXT → VERIFY',
      detail: '확인된 구조 변경은 코드와 같은 변경에서 작업 지침과 Codemap에 반영한다. 다음 작업 전에는 최신성을 다시 확인한다.',
    },
    boundary: [
      '문서와 Codemap은 탐색 기준이다. 실제 동작은 코드·데이터·테스트로 확인한다.',
      'AI가 만든 후보·검증 근거·사람의 채택 결정·기준 문서 반영을 구분해 남긴다.',
      '구현·테스트 통과·배포·실제 사용·조직 내 정착은 각각의 근거로 확인한다.',
    ],
    appliedIn: '제품 사례는 각 공개 페이지에서 확인된 근거와 boundary를 분리해 연결한다.',
  },
} as const satisfies AiNativeEngineeringContent
