import type { SecurityOperationsContent } from './content-types.ts'

export const securityOperationsContent = {
  meta: {
    classification: 'reconstructed-public-example',
    disclosure:
      '실제 제품과 운영 문서에서 확인한 구조만 남기고, 화면·이름·식별자는 공개 목적에 맞게 다시 구성했습니다.',
    boundary: {
      dataOrigin: 'independently-authored-synthetic',
      privateSourceRuntimeDependency: false,
      containsRealIdentifiers: false,
      oneToOneInternalMapping: false,
    },
  },
  hero: {
    eyebrow: 'HOW I BUILD / 04',
    titleLines: ['SECURITY &', 'OPERATIONS'],
    thesis: [
      '제품이 동작하는 것만으로는 충분하지 않았다.',
      '누가 바꿀 수 있는지, 변경을 어떻게 검증할지,',
      '실패 뒤 어디부터 사람이 판단할지까지 함께 설계했다.',
    ],
    coordinates: [
      { label: 'BOUNDARY', value: '누가 무엇을 바꾸는가' },
      { label: 'CHANGE', value: '어디에서 먼저 검증하는가' },
      { label: 'VERIFY', value: '각 신호가 무엇을 증명하는가' },
      { label: 'RECOVER', value: '어디서 자동화를 멈추는가' },
    ],
  },
  authorization: {
    eyebrow: '01 / AUTHORIZATION AS A PRODUCT',
    title: '권한을 설정이 아니라 제품으로 만들었다.',
    question: '로그인한 사람이 실제로 할 수 있는 일은 어디에서 결정되는가?',
    summary:
      '조직 계정은 신원을 확인한다. 역할의 기본값과 개인별 예외를 합친 실제 행동 권한은 제품 안에서 보고 바꾼다.',
    productLabel: 'JADEBELL HUB / ACCESS CONTROL',
    members: [
      {
        id: 'member-a',
        name: 'S. YOON',
        role: '품질 운영',
        state: '연결됨',
        selected: true,
      },
      {
        id: 'member-b',
        name: 'M. PARK',
        role: '일정 열람',
        state: '연결됨',
      },
      {
        id: 'member-c',
        name: 'H. CHOI',
        role: '템플릿 없음',
        state: '연결 대기',
      },
    ],
    templates: [
      {
        id: 'none',
        title: '템플릿 없음',
        description: '개별 권한만으로 시작',
      },
      {
        id: 'operations',
        title: '운영 조정',
        description: '일정·상태 변경',
      },
      {
        id: 'quality',
        title: '품질 기록',
        description: '조회·작성 기본값',
        selected: true,
      },
      {
        id: 'viewer',
        title: '열람 전용',
        description: '조회만 허용',
      },
    ],
    delegated: [
      {
        label: '팀원과 권한 관리',
        description: '다른 구성원의 접근 범위를 조정',
        enabled: false,
      },
      {
        label: '프로젝트 관리',
        description: '추적 대상의 표시와 보관을 관리',
        enabled: false,
      },
      {
        label: '비용과 사용량 관리',
        description: '사용량과 예산 경계를 관리',
        enabled: false,
      },
    ],
    permissionRows: [
      {
        group: 'OVERVIEW',
        resource: '개발 운영 현황',
        view: 'base',
        edit: 'none',
        manage: 'none',
      },
      {
        group: 'PROJECT',
        resource: '일정',
        view: 'base',
        edit: 'revoke',
        manage: 'none',
      },
      {
        group: 'QUALITY',
        resource: '품질 기록',
        view: 'base',
        edit: 'grant',
        manage: 'none',
      },
      {
        group: 'RECORDS',
        resource: '기록 보관함',
        view: 'grant',
        edit: 'none',
        manage: 'none',
      },
    ],
    annotations: [
      {
        id: 'template',
        index: '01',
        label: 'PERMISSION TEMPLATE',
        title: '반복되는 기본값부터 시작한다.',
        body: '역할은 매번 같은 체크박스를 다시 고르는 일을 줄이는 출발점이다. 템플릿이 없는 상태도 허용해 역할이 곧 전체 권한이라는 오해를 막았다.',
      },
      {
        id: 'override',
        index: '02',
        label: 'INDIVIDUAL OVERRIDE',
        title: '같은 역할 안의 실제 업무 차이를 남긴다.',
        body: '템플릿의 기본값 위에 사람별 허용과 회수를 별도로 둔다. 삭제와 고위험 관리는 일반 편집에서 분리했다.',
      },
      {
        id: 'effective',
        index: '03',
        label: 'EFFECTIVE PERMISSION',
        title: '보이는 설정보다 실제 결과를 확인한다.',
        body: '서버는 로그인 역할 문자열을 그대로 믿지 않는다. 활성 사용자 연결, 역할 기본값, 개인 예외를 요청마다 합쳐 실제 행동 허용을 계산한다.',
      },
      {
        id: 'guard',
        index: '04',
        label: 'ADMIN GUARD',
        title: '위임에도 넘지 못할 선을 둔다.',
        body: '위임받은 관리자는 자신을 승격하거나 상위 관리자를 바꾸고 같은 관리 권한을 다시 위임할 수 없다. 마지막 관리자 접근을 없애는 변경도 한 트랜잭션 안에서 막는다.',
      },
    ],
    formula: [
      { label: 'TEMPLATE', value: '기본값', tone: 'base' },
      { label: 'GRANT', value: '개별 허용', tone: 'grant' },
      { label: 'REVOKE', value: '개별 회수', tone: 'revoke' },
      { label: 'EFFECTIVE', value: '실제 행동', tone: 'effective' },
    ],
    evolution: [
      {
        index: '01',
        label: 'SHARED GATE',
        title: '공용 접근 제한',
        summary: '서비스 앞에서 접근을 막았지만 사람별 책임과 행동 차이를 표현하지 못했다.',
        state: 'historical',
      },
      {
        index: '02',
        label: 'IDENTITY + FIXED ROLE',
        title: '조직 계정과 고정 역할',
        summary: '사용자를 식별하고 역할별 화면과 API를 나눴다.',
        state: 'transition',
      },
      {
        index: '03',
        label: 'IDENTITY / AUTHORIZATION',
        title: '신원과 업무 권한 분리',
        summary: '로그인은 신원 경계, 실제 행동은 템플릿과 개인 예외를 합친 제품 데이터가 결정한다.',
        state: 'current',
      },
    ],
    takeaway:
      '조직과 제품 요구가 바뀌자, 권한도 고정된 역할표에서 운영 가능한 제품 surface로 바뀌었다.',
  },
  security: {
    eyebrow: '02 / SECURITY BOUNDARIES',
    title: '인증됐다는 사실만으로, 행동을 허용하지 않는다.',
    summary:
      '보안 기술의 개수보다 “어떤 실패를 허용으로 바꾸지 않을 것인가”를 먼저 정했다.',
    decisions: [
      {
        index: '01',
        risk: '로그인 성공을 업무 접근 성공으로 오해',
        decision: '조직 로그인은 신원만 확인하고, 행동 허용은 별도로 계산',
        boundary: '연결되지 않았거나 비활성인 사용자는 업무 권한이 없다.',
        evidence: 'IDENTITY ≠ AUTHORIZATION',
      },
      {
        index: '02',
        risk: '메뉴와 버튼을 숨긴 것을 보안으로 간주',
        decision: '화면과 서버 요청이 같은 resource × action 경계를 확인',
        boundary: '직접 요청해도 허용되지 않은 변경은 같은 지점에서 거부된다.',
        evidence: 'UI + SERVER',
      },
      {
        index: '03',
        risk: '세션이나 권한 저장소 오류를 오래된 허용으로 대체',
        decision: '현재 값을 확인할 수 없으면 일반화된 오류로 닫음',
        boundary: '가용성 비용을 감수하되 저장소 장애가 권한 우회가 되지 않게 한다.',
        evidence: 'FAIL CLOSED',
      },
    ],
    currentRule:
      '허용 여부를 추측해야 하는 순간에는, 진행보다 차단이 안전한 경계를 선택했다.',
  },
  deployment: {
    eyebrow: '03 / DEPLOY WITH A WAY BACK',
    title: '새 버전을 띄우는 일과, 넘겨도 되는지 판단하는 일을 분리했다.',
    summary:
      '비활성 API를 먼저 검증하고 트래픽을 넘긴다. worker는 따로 갱신하며, 데이터 계층은 같은 rollback 범위로 묶지 않는다.',
    steps: [
      {
        id: 'checks',
        index: '01',
        label: 'CHANGE',
        title: '변경과 복구 조건 확인',
        summary: '코드·권한·데이터 호환 경계를 먼저 본다.',
        proves: '배포 대상으로 삼을 변경과 사전 조건이 식별됨',
        doesNotProve: '새 버전의 runtime 정상',
        tone: 'prepare',
      },
      {
        id: 'inactive',
        index: '02',
        label: 'INACTIVE API',
        title: '비활성 대상만 기동',
        summary: '현재 트래픽을 받는 API는 그대로 둔다.',
        proves: '새 application process를 분리해 시작함',
        doesNotProve: '의존성 접근과 사용자 경로',
        tone: 'prepare',
      },
      {
        id: 'readiness',
        index: '03',
        label: 'READINESS',
        title: 'DB 접근 확인',
        summary: '전환 전에 새 API의 내부 DB query를 확인한다.',
        proves: '애플리케이션이 DB query를 수행할 수 있음',
        doesNotProve: 'Redis·worker·외부 연동·실제 권한',
        tone: 'verify',
      },
      {
        id: 'switch',
        index: '04',
        label: 'TRAFFIC SWITCH',
        title: '검증된 대상으로 전환',
        summary: 'proxy 설정을 검사한 뒤 새 API로 넘긴다.',
        proves: '전환 설정이 유효하고 적용됨',
        doesNotProve: '공개 경로가 새 대상을 응답함',
        tone: 'switch',
      },
      {
        id: 'smoke',
        index: '05',
        label: 'PUBLIC TARGET',
        title: '응답 대상 대조',
        summary: '공개 응답과 목표 대상을 함께 확인한다.',
        proves: '실제 트래픽이 새 API에 도달함',
        doesNotProve: '데이터 변경 성공과 전체 사용자 시나리오',
        tone: 'verify',
      },
      {
        id: 'worker',
        index: '06',
        label: 'WORKER',
        title: '별도 재생성과 안정성 확인',
        summary: 'API 전환과 다른 lifecycle로 갱신한다.',
        proves: '새 worker image가 실행되고 재시작이 반복되지 않음',
        doesNotProve: '모든 예약 작업의 최근 성공',
        tone: 'separate',
      },
      {
        id: 'decision',
        index: '07',
        label: 'KEEP / ROLLBACK',
        title: '기존 대상을 멈추거나 되돌림',
        summary: '검증을 모두 통과하기 전에는 이전 API를 보존한다.',
        proves: 'application traffic의 이전 경로가 남아 있음',
        doesNotProve: 'DB schema·data·Redis 상태의 rollback',
        tone: 'decision',
      },
    ],
    components: [
      {
        label: 'API',
        mode: 'SWITCHABLE',
        boundary: '비활성 대상 검증 뒤 트래픽 전환. 실패하면 이전 대상으로 복귀.',
        state: 'switchable',
      },
      {
        label: 'WORKER',
        mode: 'SEPARATE RECREATE',
        boundary: '별도 build·재생성·안정성 확인. 짧은 실행 공백 가능.',
        state: 'separate',
      },
      {
        label: 'POSTGRESQL / REDIS',
        mode: 'SHARED STATE',
        boundary: 'API traffic 전환의 rollback 대상이 아님. 호환성과 복구를 따로 판단.',
        state: 'shared',
      },
    ],
  },
  recovery: {
    eyebrow: '04 / FAILURE & RECOVERY',
    title: '재시도할 실패와, 멈춰서 볼 실패를 나눴다.',
    summary:
      '일시 오류는 좁게 다시 시도한다. 같은 실패가 계속되면 자동화를 끝내고 원인과 대상 범위를 사람이 확인한다.',
    flow: [
      {
        index: '01',
        label: 'FAILURE',
        title: '원본 저장 실패',
        detail: '성공처럼 숨기지 않고 실패 단계를 식별.',
        state: 'failure',
      },
      {
        index: '02',
        label: 'ISOLATE',
        title: '원본과 단계 보존',
        detail: '한 항목의 실패가 다음 항목을 막지 않게 격리.',
        state: 'automatic',
      },
      {
        index: '03',
        label: 'BOUNDED RETRY',
        title: '간격을 둔 세 번의 재시도',
        detail: '같은 처리 함수를 제한된 횟수로 다시 실행.',
        state: 'automatic',
      },
      {
        index: '04',
        label: 'TERMINAL',
        title: '자동 재시도 종료',
        detail: '계속 실패하면 terminal state로 격리.',
        state: 'terminal',
      },
      {
        index: '05',
        label: 'REVIEW',
        title: '원인과 범위 확인',
        detail: '읽기 전용 확인 뒤 수정할 대상을 좁힌다.',
        state: 'human',
      },
      {
        index: '06',
        label: 'REPLAY',
        title: '한 건만 수동 재실행',
        detail: '대량 재처리 전에 멱등성과 영향 범위를 확인.',
        state: 'human',
      },
    ],
    modes: [
      {
        label: 'AUTOMATED',
        title: '복구 가능한 실패를 좁게 처리',
        items: ['원본과 실패 단계 보존', '항목별 격리', '제한된 backoff와 terminal state'],
      },
      {
        label: 'ASSISTED',
        title: '도구는 실행하고, 사람은 범위를 결정',
        items: ['read-only 상태 확인', '원인 수정 뒤 단일 항목 replay', '코드 rollback 전 데이터 호환성 판단'],
      },
      {
        label: 'MANUAL / NOT VERIFIED',
        title: '자동이라고 말하지 않는 영역',
        items: ['격리 DB에서 restore 검증 뒤 전환 판단', 'full backup / restore drill', '통합 worker heartbeat·failure alert'],
      },
    ],
    knownBoundary: [
      '모든 실패가 같은 recovery path를 갖지 않는다.',
      'runbook은 선택지를 남기지만, 실행·검증 완료의 증거를 대신하지 않는다.',
      '복구율과 평균 복구 시간은 측정하지 않았다.',
    ],
  },
  boundary: {
    eyebrow: '05 / CURRENT BOUNDARY',
    title: '구현한 경계와, 아직 주장하지 않는 것.',
    summary:
      '작은 팀의 실제 제품·운영 흐름 안에서 만든 안전장치다. 이를 완성된 보안 체계나 대규모 SRE 운영으로 확대하지 않는다.',
    built: [
      '조직 로그인과 제품 업무 권한의 분리',
      '역할 템플릿 + 개인 예외 기반 권한 관리 surface',
      '요청 시점 authorization과 fail-closed 처리',
      '비활성 API 검증·전환·application rollback',
      'worker의 별도 recreate와 복원 시도',
      'bounded retry·terminal state·수동 replay',
      '구성요소별 recovery runbook',
    ],
    notClaimed: [
      'Terraform / CDK 기반 full IaC',
      '고가용성 또는 automatic DR',
      '검증 완료된 full database restore drill',
      '통합 observability와 24/7 on-call',
      '침투 테스트·보안 인증·전사 IAM 책임',
      'zero-downtime guarantee 또는 대규모 트래픽 운영',
    ],
    maintenanceRule:
      '권한 모델, 배포 구성요소, 검증 신호, 자동 복구 범위가 바뀌면 이 경계도 같은 변경에서 다시 확인한다.',
  },
  nextPage: {
    eyebrow: 'NEXT / HOW THE BOUNDARY STAYS FINDABLE',
    title: 'DOCUMENTATION SYSTEM',
    summary: '결정과 운영 경계를 어디에 두고, 무엇이 바뀌면 함께 갱신하는가.',
    href: '/how/documentation-system',
  },
} as const satisfies SecurityOperationsContent
