import type { SecurityOperationsContent } from './content-types.ts'

export const securityOperationsContent = {
  meta: {
    classification: 'reconstructed-public-example',
    disclosure:
      '제품과 운영 문서에서 확인한 설계를 바탕으로 공개용 화면과 예시를 독립적으로 재구성했습니다.',
    boundary: {
      dataOrigin: 'independently-authored-synthetic',
      privateSourceRuntimeDependency: false,
      containsRealIdentifiers: false,
      oneToOneInternalMapping: false,
    },
  },
  hero: {
    eyebrow: 'HOW I BUILD / 04',
    titleLines: ['SECURITY &', 'OPERATIONS'],
    thesis: [
      '변경 권한과 배포·복구 조건을 함께 설계했다.',
      '권한은 요청 시점에 확인하고,',
      '실패가 이어지면 자동화를 멈추고 사람이 판단한다.',
    ],
    coordinates: [
      { label: 'BOUNDARY', value: '누가 무엇을 바꾸는가' },
      { label: 'CHANGE', value: '어디에서 먼저 검증하는가' },
      { label: 'VERIFY', value: '각 신호로 어디까지 확인하는가' },
      { label: 'RECOVER', value: '어디서 자동화를 멈추는가' },
    ],
  },
  authorization: {
    eyebrow: '01 / AUTHORIZATION AS A PRODUCT',
    title: '권한을 화면에서 조정하고, 요청마다 적용한다.',
    question: '로그인한 사람이 실제로 할 수 있는 일은 어디에서 결정되는가?',
    summary:
      '조직 계정은 신원을 확인한다. 역할의 기본값과 개인별 예외를 합친 실제 행동 권한은 제품 안에서 보고 바꾼다.',
    productLabel: 'JADEBELL HUB / ACCESS CONTROL',
    members: [
      {
        id: 'member-a',
        name: 'S. YOON',
        role: '품질 운영',
        state: '연결됨',
        selected: true,
      },
      {
        id: 'member-b',
        name: 'M. PARK',
        role: '일정 열람',
        state: '연결됨',
      },
      {
        id: 'member-c',
        name: 'H. CHOI',
        role: '템플릿 없음',
        state: '연결 대기',
      },
    ],
    templates: [
      {
        id: 'none',
        title: '템플릿 없음',
        description: '개별 권한만으로 시작',
      },
      {
        id: 'operations',
        title: '운영 조정',
        description: '일정·상태 변경',
      },
      {
        id: 'quality',
        title: '품질 기록',
        description: '조회·작성 기본값',
        selected: true,
      },
      {
        id: 'viewer',
        title: '열람 전용',
        description: '조회만 허용',
      },
    ],
    delegated: [
      {
        label: '팀원과 권한 관리',
        description: '다른 구성원의 접근 범위를 조정',
        enabled: false,
      },
      {
        label: '프로젝트 관리',
        description: '추적 대상의 표시와 보관을 관리',
        enabled: false,
      },
      {
        label: '비용과 사용량 관리',
        description: '사용량과 예산 경계를 관리',
        enabled: false,
      },
    ],
    permissionRows: [
      {
        group: 'OVERVIEW',
        resource: '개발 운영 현황',
        view: 'base',
        edit: 'none',
        manage: 'none',
      },
      {
        group: 'PROJECT',
        resource: '일정',
        view: 'base',
        edit: 'revoke',
        manage: 'none',
      },
      {
        group: 'QUALITY',
        resource: '품질 기록',
        view: 'base',
        edit: 'grant',
        manage: 'none',
      },
      {
        group: 'RECORDS',
        resource: '기록 보관함',
        view: 'grant',
        edit: 'none',
        manage: 'none',
      },
    ],
    annotations: [
      {
        id: 'template',
        index: '01',
        label: 'PERMISSION TEMPLATE',
        title: '반복되는 기본값부터 시작한다.',
        body: '반복되는 권한 묶음을 템플릿으로 제공한다. 템플릿 없이 개별 권한만 부여하는 경우도 허용한다.',
      },
      {
        id: 'override',
        index: '02',
        label: 'INDIVIDUAL OVERRIDE',
        title: '같은 역할 안의 실제 업무 차이를 남긴다.',
        body: '템플릿의 기본값 위에 사람별 허용과 회수를 별도로 둔다. 삭제와 고위험 관리는 일반 편집에서 분리했다.',
      },
      {
        id: 'effective',
        index: '03',
        label: 'EFFECTIVE PERMISSION',
        title: '설정값을 합쳐 실제 행동 권한을 계산한다.',
        body: '서버는 요청마다 활성 사용자 연결, 역할 기본값, 개인별 예외를 확인해 행동 권한을 계산한다.',
      },
      {
        id: 'guard',
        index: '04',
        label: 'ADMIN GUARD',
        title: '위임에도 넘지 못할 선을 둔다.',
        body: '위임받은 관리자는 자기 자신이나 owner를 변경할 수 없고, 팀원·권한 관리 권한을 부여·회수·재위임할 수 없다. 초대 생성과 취소도 상위 관리자 전용 경계로 남긴다.',
      },
    ],
    formula: [
      { label: 'TEMPLATE', value: '기본값', tone: 'base' },
      { label: 'GRANT', value: '개별 허용', tone: 'grant' },
      { label: 'REVOKE', value: '개별 회수', tone: 'revoke' },
      { label: 'EFFECTIVE', value: '실제 행동', tone: 'effective' },
    ],
    evolution: [
      {
        index: '01',
        label: 'SHARED GATE',
        title: '공용 접근 제한',
        summary: '서비스 앞에서 접근을 막았지만 사람별 책임과 행동 차이를 표현하지 못했다.',
        state: 'historical',
      },
      {
        index: '02',
        label: 'IDENTITY + FIXED ROLE',
        title: '조직 계정과 고정 역할',
        summary: '사용자를 식별하고 역할별 화면과 API를 나눴다.',
        state: 'transition',
      },
      {
        index: '03',
        label: 'IDENTITY / AUTHORIZATION',
        title: '신원과 업무 권한 분리',
        summary: '로그인은 신원 경계, 실제 행동은 템플릿과 개인 예외를 합친 제품 데이터가 결정한다.',
        state: 'current',
      },
    ],
    takeaway:
      '고정된 역할표에서 시작해, 기본값과 개인별 예외를 화면에서 관리하는 구조로 바꿨다.',
  },
  security: {
    eyebrow: '02 / SECURITY BOUNDARIES',
    title: '신원 확인과 행동 허용을 별도로 판단한다.',
    summary:
      '사용자 연결이 없거나 현재 권한을 확인할 수 없는 경우, 접근을 허용하지 않도록 기준을 정했다.',
    decisions: [
      {
        index: '01',
        risk: '로그인 성공을 업무 접근 성공으로 오해',
        decision: '조직 로그인은 신원만 확인하고, 행동 허용은 별도로 계산',
        boundary: '연결되지 않았거나 비활성인 사용자는 업무 권한이 없다.',
        evidence: 'IDENTITY ≠ AUTHORIZATION',
      },
      {
        index: '02',
        risk: '메뉴와 버튼을 숨긴 것을 보안으로 간주',
        decision: '화면과 서버 요청에서 같은 업무 대상·행동 권한을 확인',
        boundary: '직접 요청해도 허용되지 않은 변경은 같은 지점에서 거부된다.',
        evidence: 'UI + SERVER',
      },
      {
        index: '03',
        risk: '세션이나 권한 저장소 오류를 오래된 허용으로 대체',
        decision: '현재 값을 확인할 수 없으면 공통 오류를 반환하고 요청을 차단',
        boundary: '가용성 비용을 감수하되 저장소 장애가 권한 우회가 되지 않게 한다.',
        evidence: 'FAIL CLOSED',
      },
    ],
    currentRule:
      '현재 권한을 확인할 수 없으면 요청을 차단한다.',
  },
  deployment: {
    eyebrow: '03 / DEPLOY WITH A WAY BACK',
    title: '새 버전을 띄우는 일과, 넘겨도 되는지 판단하는 일을 분리했다.',
    summary:
      '비활성 API를 먼저 검증하고 트래픽을 넘긴다. 작업 프로세스는 따로 갱신하며 데이터 복구도 별도로 판단한다.',
    steps: [
      {
        id: 'checks',
        index: '01',
        label: 'CHANGE',
        title: '변경과 복구 조건 확인',
        summary: '코드·권한·데이터 호환 경계를 먼저 본다.',
        proves: '배포 대상으로 삼을 변경과 사전 조건이 식별됨',
        doesNotProve: '새 버전의 실제 실행 상태',
        tone: 'prepare',
      },
      {
        id: 'inactive',
        index: '02',
        label: 'INACTIVE API',
        title: '비활성 대상만 기동',
        summary: '현재 트래픽을 받는 API는 그대로 둔다.',
        proves: '새 애플리케이션 프로세스를 분리해 시작함',
        doesNotProve: '의존성 접근과 사용자 경로',
        tone: 'prepare',
      },
      {
        id: 'readiness',
        index: '03',
        label: 'READINESS',
        title: 'DB 접근 확인',
        summary: '전환 전에 새 API가 내부 DB를 조회할 수 있는지 확인한다.',
        proves: '애플리케이션이 DB 조회를 수행할 수 있음',
        doesNotProve: 'Redis·작업 프로세스·외부 연동·실제 권한',
        tone: 'verify',
      },
      {
        id: 'switch',
        index: '04',
        label: 'TRAFFIC SWITCH',
        title: '검증된 대상으로 전환',
        summary: '프록시 설정을 검사한 뒤 새 API로 넘긴다.',
        proves: '전환 설정이 유효하고 적용됨',
        doesNotProve: '공개 경로가 새 대상을 응답함',
        tone: 'switch',
      },
      {
        id: 'smoke',
        index: '05',
        label: 'PUBLIC TARGET',
        title: '응답 대상 대조',
        summary: '공개 응답과 목표 대상을 함께 확인한다.',
        proves: '실제 트래픽이 새 API에 도달함',
        doesNotProve: '데이터 변경 성공과 전체 사용자 시나리오',
        tone: 'verify',
      },
      {
        id: 'worker',
        index: '06',
        label: 'WORKER',
        title: '별도 재생성과 안정성 확인',
        summary: 'API 전환과 별도 절차로 갱신한다.',
        proves: '새 작업 프로세스 이미지가 실행되고 재시작이 반복되지 않음',
        doesNotProve: '모든 예약 작업의 최근 성공',
        tone: 'separate',
      },
      {
        id: 'decision',
        index: '07',
        label: 'KEEP / ROLLBACK',
        title: '기존 대상을 멈추거나 되돌림',
        summary: '검증을 모두 통과하기 전에는 이전 API를 보존한다.',
        proves: '애플리케이션 트래픽을 이전 대상으로 되돌릴 경로가 남아 있음',
        doesNotProve: 'DB 스키마·데이터·Redis 상태의 복원',
        tone: 'decision',
      },
    ],
    components: [
      {
        label: 'API',
        mode: 'SWITCHABLE',
        boundary: '비활성 대상 검증 뒤 트래픽 전환. 실패하면 이전 대상으로 복귀.',
        state: 'switchable',
      },
      {
        label: 'WORKER',
        mode: 'SEPARATE RECREATE',
        boundary: '별도로 빌드·재생성하고 안정성을 확인한다. 짧은 실행 공백이 생길 수 있다.',
        state: 'separate',
      },
      {
        label: 'POSTGRESQL / REDIS',
        mode: 'SHARED STATE',
        boundary: 'API 트래픽을 되돌려도 데이터 상태는 복원되지 않는다. 호환성과 복구를 별도로 판단한다.',
        state: 'shared',
      },
    ],
  },
  recovery: {
    eyebrow: '04 / FAILURE & RECOVERY',
    title: '재시도할 실패와, 멈춰서 볼 실패를 나눴다.',
    summary:
      '일부 수집 실패의 일시 오류는 좁게 다시 시도한다. 같은 실패가 계속되면 자동화를 끝내고 원인과 대상 범위를 사람이 확인한다.',
    flow: [
      {
        index: '01',
        label: 'FAILURE',
        title: '원본 저장 실패',
        detail: '성공처럼 숨기지 않고 실패 단계를 식별.',
        state: 'failure',
      },
      {
        index: '02',
        label: 'ISOLATE',
        title: '원본과 단계 보존',
        detail: '한 항목의 실패가 다음 항목을 막지 않게 격리.',
        state: 'automatic',
      },
      {
        index: '03',
        label: 'BOUNDED RETRY',
        title: '간격을 둔 세 번의 재시도',
        detail: '같은 처리 함수를 제한된 횟수로 다시 실행.',
        state: 'automatic',
      },
      {
        index: '04',
        label: 'TERMINAL',
        title: '자동 재시도 종료',
        detail: '계속 실패하면 재시도를 종료한 상태로 격리.',
        state: 'terminal',
      },
      {
        index: '05',
        label: 'REVIEW',
        title: '원인과 범위 확인',
        detail: '읽기 전용 확인 뒤 수정할 대상을 좁힌다.',
        state: 'human',
      },
      {
        index: '06',
        label: 'REPLAY',
        title: '한 건만 수동 재실행',
        detail: '대량 재처리 전에 멱등성과 영향 범위를 확인.',
        state: 'human',
      },
    ],
    modes: [
      {
        label: 'AUTOMATED',
        title: '복구 가능한 실패를 좁게 처리',
        items: ['원본과 실패 단계 보존', '항목별 격리', '간격을 둔 제한 재시도와 종료 상태'],
      },
      {
        label: 'ASSISTED',
        title: '도구는 실행하고, 사람은 범위를 결정',
        items: ['상태를 바꾸지 않는 확인', '원인 수정 뒤 단일 항목 재실행', '코드를 되돌리기 전 데이터 호환성 판단'],
      },
      {
        label: 'MANUAL / NOT VERIFIED',
        title: '수동 판단과 별도 검증이 필요한 복구',
        items: ['격리된 DB에서 복원을 검증한 뒤 전환 판단', '전체 백업·복원 훈련', '작업 프로세스 통합 상태 신호·실패 알림'],
      },
    ],
    knownBoundary: [
      '실패 종류에 따라 적용하는 복구 경로가 다르다.',
      'Runbook은 복구 절차를 안내한다. 실행·검증 결과는 별도로 확인한다.',
      '복구율과 평균 복구 시간은 측정하지 않았다.',
    ],
  },
  boundary: {
    eyebrow: '05 / CURRENT BOUNDARY',
    title: '구현한 안전장치와 적용 범위',
    summary:
      '작은 팀의 제품에서 권한 관리·배포 검증·제한된 재시도를 구현했다. 자동으로 처리하는 범위와 사람이 판단할 조건을 구분해 남겼다.',
    built: [
      '조직 로그인과 제품 업무 권한의 분리',
      '역할 템플릿·개인별 예외를 조정하는 권한 관리 화면',
      '요청 시점 권한 확인·확인 실패 시 차단',
      '비활성 API 검증·전환·이전 애플리케이션으로 원복',
      '작업 프로세스의 별도 재생성과 복원 시도',
      '제한된 재시도·종료 상태·수동 재실행',
      '구성요소별 복구 절차서',
    ],
    notClaimed: [
      'Terraform / CDK 기반 전체 인프라 코드화',
      '고가용성·자동 재해 복구',
      '검증이 끝난 전체 DB 복원 훈련',
      '통합 관측 체계·24시간 상시 장애 대응',
      '침투 테스트·보안 인증·전사 IAM 책임',
      '무중단 보장·대규모 트래픽 운영',
    ],
    maintenanceRule:
      '권한 모델, 배포 구성요소, 검증 신호, 자동 복구 범위가 바뀌면 이 경계도 같은 변경에서 다시 확인한다.',
  },
  nextPage: {
    eyebrow: 'NEXT / HOW THE BOUNDARY STAYS FINDABLE',
    title: 'DOCUMENTATION SYSTEM',
    summary: '권한과 운영의 판단을 문서에 남기고, 변경에 맞춰 갱신하는 체계.',
    href: '/how/documentation-system',
  },
} as const satisfies SecurityOperationsContent
